import Foundation

nonisolated enum SSHPaths {
    static let ssh = "/usr/bin/ssh"
    static let scp = "/usr/bin/scp"

    static var supportDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appending(path: "SSHManager", directoryHint: .isDirectory)
    }

    static var configFile: URL { supportDirectory.appending(path: "ssh_config") }
    static var serversFile: URL { supportDirectory.appending(path: "servers.json") }

    /// Renames a file that failed to decode to `<name>.corrupt-<timestamp>`, so it isn't overwritten.
    /// Returns the backup location, or nil if the file couldn't be moved.
    @discardableResult
    static func backUpUnreadableFile(_ url: URL) -> URL? {
        let stamp = Date.now.formatted(.iso8601.year().month().day().time(includingFractionalSeconds: false)
            .timeSeparator(.omitted))
        let backup = url.deletingLastPathComponent()
            .appending(path: "\(url.lastPathComponent).corrupt-\(stamp)")
        do {
            try FileManager.default.moveItem(at: url, to: backup)
            return backup
        } catch {
            return nil
        }
    }

    /// Kept short: Unix socket paths are limited to ~104 characters.
    static var controlDirectory: String { "/tmp/sshmgr-\(getuid())" }
}

/// Generates an ssh_config with one `Host` alias per saved server.
/// All ssh/scp calls use `-F <this file>`, which also enables connection multiplexing
/// (ControlMaster), so browsing files after the first login is instant and needs no re-auth.
nonisolated enum SSHConfigWriter {
    static func write(servers: [Server]) throws {
        let fileManager = FileManager.default
        try fileManager.createDirectory(at: SSHPaths.supportDirectory, withIntermediateDirectories: true)

        // Without a safe socket directory, still write the config (so a stale one isn't used)
        // but with multiplexing off, then report the problem.
        var controlDirectoryError: Error?
        do { try prepareControlDirectory() } catch { controlDirectoryError = error }

        var config = "# Generated by SSH Manager. Changes will be overwritten.\n\n"
        for server in servers {
            // Values are quoted, so a stray space only breaks that one server, not the whole file.
            config += "Host \(server.alias)\n"
            config += "    HostName \(quoted(server.host))\n"
            config += "    Port \(server.port)\n"
            if !server.username.isEmpty {
                config += "    User \(quoted(server.username))\n"
            }
            switch server.authMethod {
            case .privateKey where !server.keyPath.isEmpty:
                // IdentityFile expands %-tokens, so a literal % must be doubled.
                let path = (server.keyPath as NSString).expandingTildeInPath
                    .replacingOccurrences(of: "%", with: "%%")
                config += "    IdentityFile \(quoted(path))\n"
                config += "    IdentitiesOnly yes\n"
            case .password:
                // One attempt only, so a wrong saved password doesn't trip fail2ban.
                config += "    PreferredAuthentications keyboard-interactive,password\n"
                config += "    NumberOfPasswordPrompts 1\n"
            default:
                break
            }
            config += "\n"
        }
        let multiplexing = controlDirectoryError == nil
            ? """
                  ControlMaster auto
                  ControlPath \(SSHPaths.controlDirectory)/%C
                  ControlPersist 10m
              """
            : """
                  ControlMaster no
                  ControlPath none
              """
        config += """
        Host sshmgr-*
        \(multiplexing)
            ConnectTimeout 10
            ServerAliveInterval 30
            StrictHostKeyChecking accept-new
            UserKnownHostsFile ~/.ssh/known_hosts
            LogLevel ERROR

        """

        try config.write(to: SSHPaths.configFile, atomically: true, encoding: .utf8)
        try fileManager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: SSHPaths.configFile.path)
        if let controlDirectoryError { throw controlDirectoryError }
    }

    /// Creates the multiplexing socket directory, or verifies an existing one.
    ///
    /// /tmp is shared by all users, so another account could create our directory first
    /// (or a symlink in its place) and intercept the sockets. Only a real directory owned
    /// by us with no group/other access is accepted.
    private static func prepareControlDirectory() throws {
        let path = SSHPaths.controlDirectory
        if mkdir(path, 0o700) != 0 && errno != EEXIST {
            throw SSHError("Couldn't create \(path): \(String(cString: strerror(errno)))")
        }
        var info = stat()
        guard lstat(path, &info) == 0 else {
            throw SSHError("Couldn't inspect \(path): \(String(cString: strerror(errno)))")
        }
        guard (info.st_mode & S_IFMT) == S_IFDIR, info.st_uid == getuid() else {
            throw SSHError("\(path) isn't a directory owned by you. Remove it and try again.")
        }
        if info.st_mode & 0o077 != 0, chmod(path, 0o700) != 0 {
            throw SSHError("Couldn't make \(path) private: \(String(cString: strerror(errno)))")
        }
    }

    /// Wraps a value in double quotes for ssh_config. Newlines and quotes are removed first,
    /// so user input can't end the value or inject extra config directives.
    private static func quoted(_ value: String) -> String {
        let cleaned = value.components(separatedBy: .newlines).joined()
            .replacingOccurrences(of: "\"", with: "")
            .trimmingCharacters(in: .whitespaces)
        return "\"\(cleaned)\""
    }
}

nonisolated enum SSH {
    /// POSIX single-quote escaping (also valid in fish).
    static func quote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    private static var baseArguments: [String] { ["-F", SSHPaths.configFile.path] }

    /// Runs a POSIX shell script on the server. Wrapped in `sh -c` so it works whatever the login shell is.
    @discardableResult
    static func run(_ server: Server, script: String) async throws -> String {
        let result = try await ProcessRunner.run(
            SSHPaths.ssh,
            baseArguments + [server.alias, "sh -c " + quote(script)],
            environment: AskPass.environment(for: server)
        )
        guard result.status == 0 else { throw failure(result, server: server) }
        return result.stdout
    }

    /// Turns a failed ssh/scp run into an error, explaining host key problems in plain words.
    private static func failure(_ result: ProcessResult, server: Server) -> SSHError {
        let stderr = result.stderr
        if stderr.contains("REMOTE HOST IDENTIFICATION HAS CHANGED") || stderr.contains("Host key verification failed") {
            return SSHError("""
            The host key of \(server.displayAddress) has changed since you last connected. \
            This happens after reinstalling the server, but can also mean someone is intercepting the connection.

            If you expect the change, remove the old key with:
            ssh-keygen -R \(server.port == 22 ? server.host : "[\(server.host)]:\(server.port)")
            """)
        }
        return SSHError(result.failureMessage)
    }

    /// Opens (or reuses) the multiplexed master connection.
    static func connect(_ server: Server) async throws {
        try await run(server, script: "true")
    }

    static func testConnection(_ server: Server) async throws -> String {
        let output = try await run(server, script: #"printf '%s@%s — %s\n' "$(whoami)" "$(hostname)" "$(uname -sr)""#)
        return output.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Closes the background master connection, if any.
    static func disconnect(_ server: Server) async {
        _ = try? await ProcessRunner.run(SSHPaths.ssh, baseArguments + ["-O", "exit", server.alias])
    }

    static func scp(_ arguments: [String], using server: Server) async throws {
        let result = try await ProcessRunner.run(
            SSHPaths.scp,
            baseArguments + ["-r", "-p"] + arguments,
            environment: AskPass.environment(for: server)
        )
        guard result.status == 0 else { throw failure(result, server: server) }
    }
}
